"""
Report generator — turns scored sessions into human-readable output.
"""

from datetime import datetime
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich import box
from mindcheck.scorer import SessionScore

console = Console()


def generate_report(results: list[SessionScore], period: str = "") -> str:
    """Generate a markdown report from scored sessions."""
    if not results:
        return "# MindCheck Report\n\nNo sessions to analyse.\n"

    period = period or datetime.now().strftime("%B %Y")
    avg_score = sum(r.composite for r in results) / len(results)

    best = max(results, key=lambda r: r.composite)
    worst = min(results, key=lambda r: r.composite)

    lines = [
        f"# MindCheck Report — {period}",
        "",
        f"**Cognitive Engagement Score: {avg_score:.0f}/100**",
        f"Sessions analysed: {len(results)}",
        "",
        "---",
        "",
        "## Session breakdown",
        "",
        "| Session | Tool | T1 | T2 | Hypothesis | Agency | Critical |",
        "|---|---|---|---|---|---|---|",
    ]

    for r in sorted(results, key=lambda x: x.composite, reverse=True):
        s = r.session
        sem = r.semantic
        lines.append(
            f"| {s.id[:40]} | {s.tool} | {r.tier1_score:.0f} | {r.composite:.0f} "
            f"| {sem.hypothesis_level_avg:.1f}/4 "
            f"| {sem.agency_score*100:.0f}% "
            f"| {sem.critical_engagement*100:.0f}% |"
        )

    lines += [
        "",
        "---",
        "",
        "## Highlights",
        "",
        f"**Strongest session:** {best.session.id}  ",
        f"Score: {best.composite:.0f} · "
        f"Hypothesis: {best.semantic.hypothesis_level_avg:.1f}/4",
        "",
        f"**Weakest session:** {worst.session.id}  ",
        f"Score: {worst.composite:.0f} · "
        f"Hypothesis: {worst.semantic.hypothesis_level_avg:.1f}/4",
        "",
        "---",
        "",
        "_Generated by MindCheck — https://github.com/PatrickSqx/MindCheck_",
    ]

    return "\n".join(lines)


def print_report(report_text: str):
    """Print a markdown report to the terminal with rich formatting."""
    console.print(Panel(report_text, title="[bold]MindCheck Report[/bold]", box=box.ROUNDED))


def print_session_score(result: SessionScore):
    """Print a single session's score breakdown."""
    s = result.session
    sem = result.semantic
    st = result.structural

    table = Table(title=f"Session: {s.id}", box=box.SIMPLE)
    table.add_column("Signal", style="cyan")
    table.add_column("Value", style="white")
    table.add_column("Notes", style="dim")

    table.add_row("Composite score (T2)", f"{result.composite:.0f}/100", "semantic signals")
    table.add_row("Structural score (T1)", f"{result.tier1_score:.0f}/100", "structure only")
    table.add_row("Hypothesis level",    f"{sem.hypothesis_level_avg:.1f}/4",
                  "0=no attempt, 4=tested hypothesis")
    table.add_row("Agency score",        f"{sem.agency_score*100:.0f}%",
                  "% of turns where you drove direction")
    table.add_row("Critical engagement", f"{sem.critical_engagement*100:.0f}%",
                  "pushed back / caught mistakes")
    table.add_row("Self-reliance",       f"{sem.self_reliance*100:.0f}%",
                  "showed prior attempt before asking")
    table.add_row("Metacognition",       f"{sem.metacognition_score*100:.0f}%",
                  "reflected on your own approach")
    _dp = sem.delegation_penalty * 20
    _dp_note = (
        "heavy outsourcing detected" if _dp >= 10 else
        "some outsourcing detected"  if _dp >= 3  else
        "minimal outsourcing"
    )
    table.add_row("Delegation penalty",  f"-{_dp:.1f}pts", _dp_note)
    table.add_row("Question ratio",      f"{st.question_ratio*100:.0f}%",
                  "of your messages contained a question")
    table.add_row("Turn count",          str(st.turn_count), "exchanges in session")
    table.add_row("Message ratio",       f"{st.message_ratio:.2f}",
                  "your words / AI words (higher = more engaged)")

    console.print(table)
